### ISSUE TITLE
Directive Referrer-Policy

### ISSUE THREAD

**Issue by carlitorweb** [zero-24/plg_system_httpheader#33]
Why still this warning:

**Referrer-Policy | You should explicitly set your Referrer Policy.**

If say clear I have set up this directive:

![Capture](https://user-images.githubusercontent.com/3956472/107276914-8b0b7a80-6a08-11eb-83ae-e9a024654d10.PNG)

**Comment by zero-24** [comment]
Hi,

the issue is that nowdays the "no-referrer-when-downgrade" (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy) is the default behavior so when you want to be more strict you should set the header to something more strict than that for example `same-origin` Than this issues should not come up again.

**Comment by carlitorweb** [comment]
@zero-24  Still the warning. I wrote this here, because I saw if you add, all what do the plugin directly in the .htaccess then do not show this warning. So, I was/still not sure if can be relate with the plugin 
![Captura](https://user-images.githubusercontent.com/3956472/108267481-433bd000-7139-11eb-90d1-cc2763b560e8.PNG)

**Comment by zero-24** [comment]
hmm from your sceenshot it seems there are two headers with the same name but one that is empty? Could it be a rule from the htaccess?

![image](https://user-images.githubusercontent.com/2596554/108271379-02f84400-7171-11eb-9670-fbdd4364b75a.png)

**Comment by carlitorweb** [comment]
I did not notice that. No, I not touched the .htaccess at all, but will check it. This is very strange.

**Comment by zero-24** [comment]
@carlitorweb Do you have any update here? Was that solved in the meantime? Could you find the place where the empty rule was comming from?

**Comment by carlitorweb** [comment]
@zero-24 Is not the plugin for sure, that I know 100% after test it well. So, you can close this entry. 

However, I still getting the empty referrer-policy. I checked the .htaccess and is clean. The template too. I not sure where else this can be defined, I not found any other place for search. 
![image](https://user-images.githubusercontent.com/3956472/112896527-82503000-90ac-11eb-9814-064bcced68af.png)

**Comment by zero-24** [comment]
Hmm IIRC  you could define it a bit higher on the server level maybe your hoster could take a look there?
You could also try to use: Header always set within the htaccess as that should overrule such setup. But after that I'm going to be out of ideas here sorry.

As you confirmed that its not an issue within the plugin i'm closing here for now. Feel free to update here once you found the solution. Thanks!
